'use strict';
const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const state={chapter:101,current:null,center:[12.224,-8.556],zoom:1},textures={},texturePromises={},chapterPromises={};
let w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio,2),animation=null,oldScene=null,fade=1,drag=null,touchStart=null,frame=0,requestSerial=0,catalogFilter='全部',toastTimer,lastRequest=null,tourTimer=null,tourRunning=false;
let saved={visited:[],favorites:[]};try{const v=JSON.parse(localStorage.getItem('sandbox-archive-v2')||'null');if(v)for(const k of Object.keys(saved))if(Array.isArray(v[k]))saved[k]=v[k]}catch(e){}
function save(){try{localStorage.setItem('sandbox-archive-v2',JSON.stringify(saved))}catch(e){}}
function chapterInfo(id=state.chapter){return CHAPTERS.find(c=>c.id===id)}
function chapterLabel(c){return (c.category==='主线'?String(c.id-100).padStart(2,'0')+' / ':c.category==='主线间章'?'间章 / ':'')+c.title}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function closeMore(){$('#more').hidden=true;$('#more-open').setAttribute('aria-expanded','false')}

function setUIHidden(hidden){closeMore();$('#intro').hidden=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.body.classList.toggle('ui-hidden',hidden);$('#restore-ui').hidden=!hidden;if(hidden)$('#restore-ui').focus({preventScroll:true});else $('#more-open').focus({preventScroll:true})}
$('#hide-ui').onclick=()=>setUIHidden(true);$('#restore-ui').onclick=()=>setUIHidden(false);

function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio,2);canvas.width=w*dpr;canvas.height=h*dpr;draw()}
function draw(){constrainView();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#454b41';ctx.fillRect(0,0,w,h);render(state.current,1);if(oldScene&&fade<1)render(oldScene,1-fade)}
function episodes(){return SCENESETS[state.chapter]||[]}
function neighbors(){const el=$('#neighbors');el.replaceChildren();const list=episodes(),idx=list.indexOf(state.current);for(const s of list){const b=document.createElement('button');b.className='episode'+(s===state.current?' active':'');b.setAttribute('aria-current',s===state.current?'step':'false');const row=document.createElement('div'),n=document.createElement('b'),star=document.createElement('i'),title=document.createElement('h2'),english=document.createElement('p'),date=document.createElement('time');n.textContent=String(s.number).padStart(2,'0');star.textContent='✦';row.append(n,star);title.textContent=s.title;english.textContent=s.title_fallback?'':s.english;date.textContent=s.date;b.append(row,title,english,date);b.onclick=()=>{stopTour();select(s.id)};el.append(b)}$('#timeline-position').textContent=String(idx+1).padStart(2,'0')+' / '+list.length;$('#previous').disabled=idx<=0;$('#next').disabled=idx>=list.length-1;requestAnimationFrame(()=>{const active=el.querySelector('.active');if(active)el.scrollTo({left:active.offsetLeft-el.offsetLeft-(el.clientWidth-active.clientWidth)/2,behavior:reduced?'instant':'smooth'})})}
function syncUI(scene){const c=chapterInfo();$('#chapter-label').textContent=c.category==='主线'?'主线 · 第'+(c.id-100)+'章':c.category;$('#chapter-name').textContent=c.title;$('#chapter-subtitle').textContent=c.english;$('#scene-date').textContent=(scene.year?scene.year+' · ':'')+scene.date;const favorite=saved.favorites.includes(scene.id);$('#favorite').setAttribute('aria-pressed',favorite);$('#favorite').textContent=favorite?'已收藏':'收藏';neighbors()}
async function select(id,instant=false,cid=state.chapter){const token=++requestSerial;lastRequest={id,cid};$('#loading').hidden=false;$('#error').hidden=true;try{const list=await loadChapter(cid),scene=list.find(s=>s.id===id)||list[0];if(!scene)throw new Error('Scene unavailable');await loadTextures(scene);if(token!==requestSerial)return false;const changing=state.chapter!==cid;state.chapter=cid;SCENES=SCENESETS[cid];oldScene=state.current;state.current=scene;if(!saved.visited.includes(scene.id)){saved.visited.push(scene.id);save()}syncUI(scene);if(changing)state.zoom=1;moveTo(scene.center,instant||changing);$('#loading').hidden=true;window.SANDBOX_READY=true;return true;}catch(e){if(token!==requestSerial)return false;$('#loading').hidden=true;$('#error').hidden=false;stopTour();console.error(e);return false}}
async function changeChapter(cid,id){const c=chapterInfo(cid);if(!c||!c.count)return;stopTour();closeMore();$('#intro').hidden=true;if(await select(id||c.episodes[0].id,false,cid))$('#album').close()}
function openAlbum(){stopTour();catalog();$('#intro').hidden=true;closeMore();if(!$('#album').open)$('#album').showModal()}
function catalog(){const q=$('#album-search').value.trim().toLowerCase(),grid=$('#album-grid');grid.replaceChildren();const shown=CHAPTERS.filter(c=>c.count&&(catalogFilter==='全部'||catalogFilter==='收藏'&&c.episodes.some(e=>saved.favorites.includes(e.id))||catalogFilter==='主线'&&['主线','主线间章'].includes(c.category)||c.category===catalogFilter)&&(!q||`${c.title} ${c.english} ${c.episodes.map(e=>e.title).join(' ')}`.toLowerCase().includes(q)));for(const c of shown){const b=document.createElement('button');b.className='chapter-card';b.dataset.chapter=c.id;const img=document.createElement('img');img.src=`assets/covers/${c.id}.webp`;img.alt='';img.loading='lazy';const meta=document.createElement('div');meta.className='card-meta';const category=document.createElement('span'),count=document.createElement('span');category.textContent=c.category;count.textContent=c.count+' 幕';meta.append(category,count);const title=document.createElement('h3'),sub=document.createElement('p');title.textContent=chapterLabel(c);sub.textContent=c.english;b.append(img,meta,title,sub);b.onclick=()=>{const matches=c.episodes.filter(e=>(catalogFilter!=='收藏'||saved.favorites.includes(e.id))&&(!q||`${c.title} ${c.english}`.toLowerCase().includes(q)||e.title.toLowerCase().includes(q)));changeChapter(c.id,matches[0]?.id)};grid.append(b)}$('#album-count').textContent=shown.length+' 个章节';$('#album-empty').hidden=!!shown.length}
function openTimeline(){stopTour();closeMore();const d=$('#timeline');$('#timeline-title').textContent=chapterInfo().title;const el=$('#timeline-list');el.replaceChildren();for(const s of episodes()){const b=document.createElement('button'),n=document.createElement('span'),t=document.createElement('div'),sub=document.createElement('small');n.textContent=String(s.number).padStart(2,'0');t.textContent=s.title;sub.textContent=s.date+(s.english&&!s.title_fallback?' · '+s.english:'');t.append(sub);b.append(n,t);b.setAttribute('aria-current',s===state.current?'true':'false');b.onclick=()=>{d.close();select(s.id)};el.append(b)}d.showModal();requestAnimationFrame(()=>el.querySelector('[aria-current=true]')?.scrollIntoView({block:'nearest'}))}
function randomScene(){stopTour();const list=CHAPTERS.flatMap(c=>c.count?c.episodes.map(e=>({id:e.id,cid:c.id})):[]).filter(e=>e.id!==state.current?.id);const e=list[Math.floor(Math.random()*list.length)];if(e)changeChapter(e.cid,e.id)}
function tourUI(){$('#tour').setAttribute('aria-pressed',tourRunning);$('#tour').firstChild.textContent=tourRunning?'暂停漫游 ':'沿途漫游 '}
function stopTour(){clearTimeout(tourTimer);tourTimer=null;tourRunning=false;tourUI()}
function scheduleTour(){clearTimeout(tourTimer);if(!tourRunning||document.hidden)return;tourTimer=setTimeout(async()=>{if(!tourRunning)return;const list=episodes(),idx=list.indexOf(state.current);if(idx===list.length-1){stopTour();toast('这一章的风景，已走到末尾。');return}if(await select(list[idx+1].id)){if(tourRunning)scheduleTour()}},6500)}
$('#album-open').onclick=openAlbum;$('#album-close').onclick=()=>$('#album').close();$('#album-search').oninput=catalog;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{catalogFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));catalog()});$('#timeline-open').onclick=openTimeline;$('#timeline-position').onclick=openTimeline;$('#previous').onclick=()=>{stopTour();const list=episodes(),s=list[list.indexOf(state.current)-1];if(s)select(s.id)};$('#next').onclick=()=>{stopTour();const list=episodes(),s=list[list.indexOf(state.current)+1];if(s)select(s.id)};
$('#favorite').onclick=()=>{if(!state.current)return;const id=state.current.id,i=saved.favorites.indexOf(id);if(i<0)saved.favorites.push(id);else saved.favorites.splice(i,1);save();syncUI(state.current);toast(i<0?'已收藏这一幕。':'已移出收藏。')};$('#more-open').onclick=()=>{$('#more').hidden=!$('#more').hidden;$('#more-open').setAttribute('aria-expanded',!$('#more').hidden)};$('#home').onclick=()=>{stopTour();closeMore();state.zoom=1;if(state.current)moveTo(state.current.center)};$('#random').onclick=randomScene;$('#tour').onclick=()=>{if(!state.current)return;if(tourRunning){stopTour();toast('已暂停漫游。')}else{tourRunning=true;tourUI();scheduleTour();toast('沿途漫游已开始，拖动沙盘可暂停。')}closeMore()};$('#help-open').onclick=()=>{stopTour();closeMore();$('#help').showModal()};$('#help-done').onclick=()=>$('#help').close();$('#intro-close').onclick=()=>{$('#intro').hidden=true;try{localStorage.setItem('sandbox-intro-v4','1')}catch(e){}};$('#retry').onclick=()=>{if(lastRequest)select(lastRequest.id,false,lastRequest.cid)};$('#error-album').onclick=()=>{$('#error').hidden=true;openAlbum()};$('#full').onclick=async()=>{closeMore();try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){toast('可以使用浏览器的全屏功能。')}};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close()}));
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key.toLowerCase()==='u'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();setUIHidden(!document.body.classList.contains('ui-hidden'));return}if(e.key==='Escape'&&document.body.classList.contains('ui-hidden')){setUIHidden(false);return}const list=episodes(),i=list.indexOf(state.current);if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stopTour();const s=list[i+(e.key==='ArrowLeft'?-1:1)];if(s)select(s.id)}if(e.key==='Home')$('#home').click();if(e.key.toLowerCase()==='r')randomScene();if(e.key==='Escape')closeMore()});addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(tourTimer);else scheduleTour()});
resize();select(10101,true,101).then(ok=>{if(ok){try{if(!localStorage.getItem('sandbox-intro-v4'))$('#intro').hidden=false}catch(e){}}});
canvas.addEventListener('pointerdown',e=>{if(!state.current)return;$('#more').hidden=true;$('#more-open').setAttribute('aria-expanded','false');stopTour();cancelAnimationFrame(frame);animation=null;oldScene=null;fade=1;drag={x:e.clientX,y:e.clientY,from:[...state.center],moved:false};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved=drag.moved||Math.hypot(dx,dy)>4;state.center=[drag.from[0]-dx/scale(),drag.from[1]+dy/scale()];draw()});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
function zoomAt(z,x,y){const old=scale(),world=[(x-w/2)/old+state.center[0],-(y-h*.47)/old+state.center[1]];state.zoom=Math.max(minimumZoom(),Math.min(Math.max(2.7,minimumZoom()*3),z));state.center=[world[0]-(x-w/2)/scale(),world[1]+(y-h*.47)/scale()];draw()}
canvas.addEventListener('wheel',e=>{e.preventDefault();cancelAnimationFrame(frame);animation=null;oldScene=null;fade=1;zoomAt(state.zoom*Math.exp(-e.deltaY*.001),e.clientX,e.clientY)},{passive:false});canvas.addEventListener('touchstart',e=>{if(e.touches.length===2){drag=null;touchStart={distance:Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY),zoom:state.zoom}}},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2&&touchStart){e.preventDefault();drag=null;const [a,b]=e.touches;zoomAt(touchStart.zoom*Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)/touchStart.distance,(a.clientX+b.clientX)/2,(a.clientY+b.clientY)/2)}},{passive:false});canvas.addEventListener('touchend',()=>touchStart=null);

// Native touch swipe, mouse wheel and mouse drag all navigate the same strip.
const strip=$('#neighbors');let stripDrag=null,stripClickMoved=false;
strip.addEventListener('wheel',e=>{if(strip.scrollWidth<=strip.clientWidth)return;e.preventDefault();strip.scrollLeft+=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY},{passive:false});
strip.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;stripClickMoved=false;stripDrag={id:e.pointerId,x:e.clientX,left:strip.scrollLeft};});
strip.addEventListener('pointermove',e=>{if(!stripDrag)return;const dx=e.clientX-stripDrag.x;if(Math.abs(dx)>6&&!stripClickMoved){stripClickMoved=true;strip.setPointerCapture(e.pointerId);strip.classList.add('dragging');}if(stripClickMoved){strip.scrollLeft=stripDrag.left-dx;e.preventDefault();}});
function endStripDrag(){stripDrag=null;strip.classList.remove('dragging')}
strip.addEventListener('pointerup',endStripDrag);strip.addEventListener('pointercancel',endStripDrag);
strip.addEventListener('click',e=>{if(stripClickMoved&&e.detail){e.preventDefault();e.stopImmediatePropagation();stripClickMoved=false;}},true);
