// Translated from the extracted fx_smoke_position GLES fragment program.
// Chapter hole positions follow DungeonMapHoleView: param + worldPos - initPos.
let fogRenderer;
function makeFogRenderer(){
 const surface=document.createElement('canvas'),gl=surface.getContext('webgl',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true,antialias:false});
 if(!gl)return makeCPUFogRenderer();
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 aScreen; attribute vec2 aWorld; varying vec2 world; void main(){world=aWorld;gl_Position=vec4(aScreen,0.,1.);}'));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision highp float; varying vec2 world; uniform vec4 holes[5]; uniform vec4 distort; uniform vec4 color; uniform bool smoothing; void main(){float alpha=color.a;for(int i=0;i<5;i++){vec2 delta=(world-holes[i].xy)*vec2(1.,distort.z)*distort.w;float a=clamp((length(delta)+holes[i].z)*distort.x+distort.y,0.,1.);if(smoothing&&i<4)a=a*a*a*(3.-2.*a);alpha*=a;}gl_FragColor=vec4(color.rgb,alpha);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));
 const buffer=gl.createBuffer(),screen=gl.getAttribLocation(program,'aScreen'),world=gl.getAttribLocation(program,'aWorld'),uniforms=Object.fromEntries(['holes[0]','distort','color','smoothing'].map(k=>[k,gl.getUniformLocation(program,k)]));
 return {surface,draw(layer,holes){if(surface.width!==canvas.width||surface.height!==canvas.height){surface.width=canvas.width;surface.height=canvas.height}gl.viewport(0,0,surface.width,surface.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const data=[];for(const face of layer.faces)for(let i=1;i<face.length-1;i++)for(const idx of [face[0],face[i],face[i+1]]){const v=layer.vertices[idx],p=project(v);data.push(p[0]/w*2-1,1-p[1]/h*2,v[0],v[1])}gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(screen);gl.vertexAttribPointer(screen,2,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(world);gl.vertexAttribPointer(world,2,gl.FLOAT,false,16,8);gl.uniform4fv(uniforms['holes[0]'],new Float32Array(holes.flat()));gl.uniform4fv(uniforms.distort,layer.distort);gl.uniform4fv(uniforms.color,layer.color);gl.uniform1i(uniforms.smoothing,layer.smooth?1:0);gl.drawArrays(gl.TRIANGLES,0,data.length/4)}};
}

function makeCPUFogRenderer(){const surface=document.createElement('canvas'),c=surface.getContext('2d');return {surface,draw(layer,holes){const ratio=Math.min(1,520/w);surface.width=Math.max(1,Math.round(w*ratio));surface.height=Math.max(1,Math.round(h*ratio));const im=c.createImageData(surface.width,surface.height),sc=scale(),[a,b,ellipse,radius]=layer.distort;for(let y=0;y<surface.height;y++)for(let x=0;x<surface.width;x++){const wx=(x/ratio-w/2)/sc+state.center[0],wy=-(y/ratio-h*.47)/sc+state.center[1];let alpha=layer.color[3];for(let i=0;i<5;i++){const hole=holes[i];let q=Math.max(0,Math.min(1,(Math.hypot(wx-hole[0],(wy-hole[1])*ellipse)*radius+hole[2])*a+b));if(layer.smooth&&i<4)q=q*q*q*(3-2*q);alpha*=q}const idx=(y*surface.width+x)*4;for(let k=0;k<3;k++)im.data[idx+k]=layer.color[k]*255;im.data[idx+3]=alpha*255}c.putImageData(im,0,0);c.globalCompositeOperation='destination-in';c.beginPath();for(const face of layer.faces){face.forEach((idx,i)=>{const xy=project(layer.vertices[idx]);if(i)c.lineTo(xy[0]*ratio,xy[1]*ratio);else c.moveTo(xy[0]*ratio,xy[1]*ratio)});c.closePath()}c.fill();c.globalCompositeOperation='source-over'}}}

function renderFog(scene,opacity=1){const fog=scene&&FOG_DATA[scene.id];if(!fog?.holes?.length)return;try{if(fogRenderer===undefined)fogRenderer=makeFogRenderer();if(!fogRenderer)return;const holes=Array.from({length:5},()=>[10000,10000,100,0]);for(const hole of fog.holes){if(hole.index<1||hole.index>5)continue;holes[hole.index-1]=[hole.vector[0]+fog.center[0],hole.vector[1]+fog.center[1],hole.vector[2],0]}for(const layer of fog.layers){if(layer.texture?.m_PathID)continue;fogRenderer.draw(layer,holes);ctx.save();ctx.globalAlpha=opacity;ctx.drawImage(fogRenderer.surface,0,0,w,h);ctx.restore()}}catch(e){fogRenderer=null;console.error('Fog renderer unavailable',e)}}
